package com.suyang.aDemo.dao;

import com.suyang.aDemo.dao.DemoStudentExample;
import com.suyang.aDemo.model.DemoStudent;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int countByExample(DemoStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int deleteByExample(DemoStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int insert(DemoStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int insertSelective(DemoStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    List<DemoStudent> selectByExample(DemoStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    DemoStudent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByExampleSelective(@Param("record") DemoStudent record, @Param("example") DemoStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByExample(@Param("record") DemoStudent record, @Param("example") DemoStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByPrimaryKeySelective(DemoStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_student
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByPrimaryKey(DemoStudent record);
}