package com.suyang.aDemo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.suyang.aDemo.model.DemoClass;

public interface DemoClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int countByExample(DemoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int deleteByExample(DemoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int insert(DemoClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int insertSelective(DemoClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    List<DemoClass> selectByExample(DemoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    DemoClass selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByExampleSelective(@Param("record") DemoClass record, @Param("example") DemoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByExample(@Param("record") DemoClass record, @Param("example") DemoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByPrimaryKeySelective(DemoClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_class
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByPrimaryKey(DemoClass record);
}