package com.suyang.aDemo.dao;

import com.suyang.aDemo.dao.DemoUserAdminExample;
import com.suyang.aDemo.model.DemoUserAdmin;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoUserAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    int countByExample(DemoUserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    int deleteByExample(DemoUserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    int insert(DemoUserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    int insertSelective(DemoUserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    List<DemoUserAdmin> selectByExample(DemoUserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    DemoUserAdmin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    int updateByExampleSelective(@Param("record") DemoUserAdmin record, @Param("example") DemoUserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    int updateByExample(@Param("record") DemoUserAdmin record, @Param("example") DemoUserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    int updateByPrimaryKeySelective(DemoUserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_admin
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    int updateByPrimaryKey(DemoUserAdmin record);
}