package com.suyang.aDemo.dao;

import com.suyang.aDemo.dao.DemoUserCourseExample;
import com.suyang.aDemo.model.DemoUserCourse;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoUserCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    int countByExample(DemoUserCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    int deleteByExample(DemoUserCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    int insert(DemoUserCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    int insertSelective(DemoUserCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    List<DemoUserCourse> selectByExample(DemoUserCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    DemoUserCourse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    int updateByExampleSelective(@Param("record") DemoUserCourse record, @Param("example") DemoUserCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    int updateByExample(@Param("record") DemoUserCourse record, @Param("example") DemoUserCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    int updateByPrimaryKeySelective(DemoUserCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_course
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    int updateByPrimaryKey(DemoUserCourse record);
}