package com.suyang.aDemo.dao;

import com.suyang.aDemo.dao.DemoTeacherExample;
import com.suyang.aDemo.model.DemoTeacher;
import com.suyang.aDemo.model.pojo.vo.TeacherVO;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int countByExample(DemoTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int deleteByExample(DemoTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int insert(DemoTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int insertSelective(DemoTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    List<DemoTeacher> selectByExample(DemoTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    DemoTeacher selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByExampleSelective(@Param("record") DemoTeacher record, @Param("example") DemoTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByExample(@Param("record") DemoTeacher record, @Param("example") DemoTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByPrimaryKeySelective(DemoTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByPrimaryKey(DemoTeacher record);
    
    List<TeacherVO> getFullTeacherList();
    
    TeacherVO getFullTeacherById(Long id);
}