package com.suyang.aDemo.dao;

import com.suyang.aDemo.dao.DemoTeacherCourseExample;
import com.suyang.aDemo.model.DemoTeacherCourse;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoTeacherCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int countByExample(DemoTeacherCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int deleteByExample(DemoTeacherCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int insert(DemoTeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int insertSelective(DemoTeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    List<DemoTeacherCourse> selectByExample(DemoTeacherCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    DemoTeacherCourse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByExampleSelective(@Param("record") DemoTeacherCourse record, @Param("example") DemoTeacherCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByExample(@Param("record") DemoTeacherCourse record, @Param("example") DemoTeacherCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByPrimaryKeySelective(DemoTeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_teacher_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByPrimaryKey(DemoTeacherCourse record);
}