package com.suyang.aDemo.dao;

import com.suyang.aDemo.dao.DemoCourseExample;
import com.suyang.aDemo.model.DemoCourse;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int countByExample(DemoCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int deleteByExample(DemoCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int insert(DemoCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int insertSelective(DemoCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    List<DemoCourse> selectByExample(DemoCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    DemoCourse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByExampleSelective(@Param("record") DemoCourse record, @Param("example") DemoCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByExample(@Param("record") DemoCourse record, @Param("example") DemoCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByPrimaryKeySelective(DemoCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_course
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    int updateByPrimaryKey(DemoCourse record);
}