package com.suyang.aDemo.model;

public class DemoUserAdmin extends BaseBean{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6956149837652229730L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_admin.id
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_admin.user_type
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    private Boolean userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_admin.user_id
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_admin.admin_id
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    private Long adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_admin.id
     *
     * @return the value of demo_user_admin.id
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_admin.id
     *
     * @param id the value for demo_user_admin.id
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_admin.user_type
     *
     * @return the value of demo_user_admin.user_type
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    public Boolean getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_admin.user_type
     *
     * @param userType the value for demo_user_admin.user_type
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    public void setUserType(Boolean userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_admin.user_id
     *
     * @return the value of demo_user_admin.user_id
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_admin.user_id
     *
     * @param userId the value for demo_user_admin.user_id
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_admin.admin_id
     *
     * @return the value of demo_user_admin.admin_id
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_admin.admin_id
     *
     * @param adminId the value for demo_user_admin.admin_id
     *
     * @mbggenerated Tue May 28 16:44:01 SGT 2019
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }
}