package com.suyang.aDemo.model;

import java.util.Date;

public class DemoStudent extends BaseBean{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3693522110955707097L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_student.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_student.genter
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Boolean genter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_student.age
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_student.name
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_student.class_id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_student.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_student.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Date createdDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_student.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_student.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Date updatedDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_student.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_student.id
     *
     * @return the value of demo_student.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_student.id
     *
     * @param id the value for demo_student.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_student.genter
     *
     * @return the value of demo_student.genter
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Boolean getGenter() {
        return genter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_student.genter
     *
     * @param genter the value for demo_student.genter
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setGenter(Boolean genter) {
        this.genter = genter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_student.age
     *
     * @return the value of demo_student.age
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_student.age
     *
     * @param age the value for demo_student.age
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_student.name
     *
     * @return the value of demo_student.name
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_student.name
     *
     * @param name the value for demo_student.name
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_student.class_id
     *
     * @return the value of demo_student.class_id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_student.class_id
     *
     * @param classId the value for demo_student.class_id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_student.is_active
     *
     * @return the value of demo_student.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_student.is_active
     *
     * @param isActive the value for demo_student.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setIsActive(Long isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_student.created_dttm
     *
     * @return the value of demo_student.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Date getCreatedDttm() {
        return createdDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_student.created_dttm
     *
     * @param createdDttm the value for demo_student.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_student.created_by
     *
     * @return the value of demo_student.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_student.created_by
     *
     * @param createdBy the value for demo_student.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_student.updated_dttm
     *
     * @return the value of demo_student.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Date getUpdatedDttm() {
        return updatedDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_student.updated_dttm
     *
     * @param updatedDttm the value for demo_student.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_student.updated_by
     *
     * @return the value of demo_student.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_student.updated_by
     *
     * @param updatedBy the value for demo_student.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }
}