package com.suyang.aDemo.model;

public class DemoTeacherCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher_course.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher_course.teacher_id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher_course.course_id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher_course.id
     *
     * @return the value of demo_teacher_course.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher_course.id
     *
     * @param id the value for demo_teacher_course.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher_course.teacher_id
     *
     * @return the value of demo_teacher_course.teacher_id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher_course.teacher_id
     *
     * @param teacherId the value for demo_teacher_course.teacher_id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher_course.course_id
     *
     * @return the value of demo_teacher_course.course_id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher_course.course_id
     *
     * @param courseId the value for demo_teacher_course.course_id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }
}