package com.suyang.aDemo.model;

public class DemoUserCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_course.id
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_course.user_id
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_course.course_id
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    private Long courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_course.user_type
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    private Boolean userType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_course.id
     *
     * @return the value of demo_user_course.id
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_course.id
     *
     * @param id the value for demo_user_course.id
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_course.user_id
     *
     * @return the value of demo_user_course.user_id
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_course.user_id
     *
     * @param userId the value for demo_user_course.user_id
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_course.course_id
     *
     * @return the value of demo_user_course.course_id
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_course.course_id
     *
     * @param courseId the value for demo_user_course.course_id
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_course.user_type
     *
     * @return the value of demo_user_course.user_type
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    public Boolean getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_course.user_type
     *
     * @param userType the value for demo_user_course.user_type
     *
     * @mbggenerated Tue May 28 18:41:25 SGT 2019
     */
    public void setUserType(Boolean userType) {
        this.userType = userType;
    }
}