package com.suyang.aDemo.model;

import java.util.Date;

public class DemoClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_class.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_class.class_code
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_class.grade
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_class.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_class.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Date createdDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_class.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_class.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Date updatedDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_class.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_class.id
     *
     * @return the value of demo_class.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_class.id
     *
     * @param id the value for demo_class.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_class.class_code
     *
     * @return the value of demo_class.class_code
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_class.class_code
     *
     * @param classCode the value for demo_class.class_code
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_class.grade
     *
     * @return the value of demo_class.grade
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_class.grade
     *
     * @param grade the value for demo_class.grade
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_class.is_active
     *
     * @return the value of demo_class.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_class.is_active
     *
     * @param isActive the value for demo_class.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_class.created_dttm
     *
     * @return the value of demo_class.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Date getCreatedDttm() {
        return createdDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_class.created_dttm
     *
     * @param createdDttm the value for demo_class.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_class.created_by
     *
     * @return the value of demo_class.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_class.created_by
     *
     * @param createdBy the value for demo_class.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_class.updated_dttm
     *
     * @return the value of demo_class.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Date getUpdatedDttm() {
        return updatedDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_class.updated_dttm
     *
     * @param updatedDttm the value for demo_class.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_class.updated_by
     *
     * @return the value of demo_class.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_class.updated_by
     *
     * @param updatedBy the value for demo_class.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }
}