package com.suyang.aDemo.model;

import java.util.Date;

public class DemoCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_course.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_course.course_name
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_course.course_desc
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private String courseDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_course.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_course.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Date createdDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_course.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_course.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Date updatedDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_course.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_course.id
     *
     * @return the value of demo_course.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_course.id
     *
     * @param id the value for demo_course.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_course.course_name
     *
     * @return the value of demo_course.course_name
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_course.course_name
     *
     * @param courseName the value for demo_course.course_name
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_course.course_desc
     *
     * @return the value of demo_course.course_desc
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public String getCourseDesc() {
        return courseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_course.course_desc
     *
     * @param courseDesc the value for demo_course.course_desc
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCourseDesc(String courseDesc) {
        this.courseDesc = courseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_course.is_active
     *
     * @return the value of demo_course.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_course.is_active
     *
     * @param isActive the value for demo_course.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_course.created_dttm
     *
     * @return the value of demo_course.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Date getCreatedDttm() {
        return createdDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_course.created_dttm
     *
     * @param createdDttm the value for demo_course.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_course.created_by
     *
     * @return the value of demo_course.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_course.created_by
     *
     * @param createdBy the value for demo_course.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_course.updated_dttm
     *
     * @return the value of demo_course.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Date getUpdatedDttm() {
        return updatedDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_course.updated_dttm
     *
     * @param updatedDttm the value for demo_course.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_course.updated_by
     *
     * @return the value of demo_course.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_course.updated_by
     *
     * @param updatedBy the value for demo_course.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }
}