package com.suyang.aDemo.model;

import java.util.Date;

public class DemoTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher.name
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher.genter
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Boolean genter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Date createdDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    private Date updatedDttm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher.id
     *
     * @return the value of demo_teacher.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher.id
     *
     * @param id the value for demo_teacher.id
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher.name
     *
     * @return the value of demo_teacher.name
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher.name
     *
     * @param name the value for demo_teacher.name
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher.genter
     *
     * @return the value of demo_teacher.genter
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Boolean getGenter() {
        return genter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher.genter
     *
     * @param genter the value for demo_teacher.genter
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setGenter(Boolean genter) {
        this.genter = genter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher.is_active
     *
     * @return the value of demo_teacher.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher.is_active
     *
     * @param isActive the value for demo_teacher.is_active
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher.created_by
     *
     * @return the value of demo_teacher.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher.created_by
     *
     * @param createdBy the value for demo_teacher.created_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher.created_dttm
     *
     * @return the value of demo_teacher.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Date getCreatedDttm() {
        return createdDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher.created_dttm
     *
     * @param createdDttm the value for demo_teacher.created_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher.updated_by
     *
     * @return the value of demo_teacher.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher.updated_by
     *
     * @param updatedBy the value for demo_teacher.updated_by
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher.updated_dttm
     *
     * @return the value of demo_teacher.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public Date getUpdatedDttm() {
        return updatedDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher.updated_dttm
     *
     * @param updatedDttm the value for demo_teacher.updated_dttm
     *
     * @mbggenerated Tue May 28 16:37:59 SGT 2019
     */
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
}