package com.suyang.aDemo.model;

public class DemoTeacherClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher_class.id
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher_class.teacher_id
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher_class.class_id
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_teacher_class.teacher_type
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    private Boolean teacherType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher_class.id
     *
     * @return the value of demo_teacher_class.id
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher_class.id
     *
     * @param id the value for demo_teacher_class.id
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher_class.teacher_id
     *
     * @return the value of demo_teacher_class.teacher_id
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher_class.teacher_id
     *
     * @param teacherId the value for demo_teacher_class.teacher_id
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher_class.class_id
     *
     * @return the value of demo_teacher_class.class_id
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher_class.class_id
     *
     * @param classId the value for demo_teacher_class.class_id
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_teacher_class.teacher_type
     *
     * @return the value of demo_teacher_class.teacher_type
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    public Boolean getTeacherType() {
        return teacherType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_teacher_class.teacher_type
     *
     * @param teacherType the value for demo_teacher_class.teacher_type
     *
     * @mbggenerated Tue May 28 19:03:27 SGT 2019
     */
    public void setTeacherType(Boolean teacherType) {
        this.teacherType = teacherType;
    }
}