package com.suyang.aDemo.template;

public class DemoAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_admin.id
     *
     * @mbggenerated Tue May 28 16:25:35 SGT 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_admin.name
     *
     * @mbggenerated Tue May 28 16:25:35 SGT 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_admin.admin_level
     *
     * @mbggenerated Tue May 28 16:25:35 SGT 2019
     */
    private Boolean adminLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_admin.id
     *
     * @return the value of demo_admin.id
     *
     * @mbggenerated Tue May 28 16:25:35 SGT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_admin.id
     *
     * @param id the value for demo_admin.id
     *
     * @mbggenerated Tue May 28 16:25:35 SGT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_admin.name
     *
     * @return the value of demo_admin.name
     *
     * @mbggenerated Tue May 28 16:25:35 SGT 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_admin.name
     *
     * @param name the value for demo_admin.name
     *
     * @mbggenerated Tue May 28 16:25:35 SGT 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_admin.admin_level
     *
     * @return the value of demo_admin.admin_level
     *
     * @mbggenerated Tue May 28 16:25:35 SGT 2019
     */
    public Boolean getAdminLevel() {
        return adminLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_admin.admin_level
     *
     * @param adminLevel the value for demo_admin.admin_level
     *
     * @mbggenerated Tue May 28 16:25:35 SGT 2019
     */
    public void setAdminLevel(Boolean adminLevel) {
        this.adminLevel = adminLevel;
    }
}